name: Build UEFI Cube

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GNU-EFI
      run: |
        sudo apt-get update
        sudo apt-get install -y gnu-efi git build-essential

    - name: Compile UEFI app
      run: |
        # Set up GNU-EFI paths
        export GNU_EFI_INCLUDE="/usr/include/efi"
        export GNU_EFI_LIB="/usr/lib"

        # Compile
        x86_64-w64-mingw32-gcc \
          -I"$GNU_EFI_INCLUDE" -I"$GNU_EFI_INCLUDE/x86_64" \
          -nostdinc -nostdlib -fno-builtin \
          -fpic -ffreestanding -fshort-wchar \
          -mno-red-zone \
          -Wall -Wextra \
          -e efi_main \
          -Wl,--subsystem,10 \
          -o cube.efi cube.c \
          -L"$GNU_EFI_LIB" -lgnuefi -lefi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cube.efi
        path: cube.efi
