name: Build UEFI App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GNU-EFI
        run: |
          sudo apt-get update
          sudo apt-get install -y gnu-efi

      - name: Compile
        run: |
          # Set paths
          INCLUDE="/usr/include/efi"
          LIB="/usr/lib"

          # Build command
          x86_64-linux-gnu-gcc \
            -I"$INCLUDE" -I"$INCLUDE/x86_64" \
            -nostdinc -nostdlib -fno-builtin \
            -fpic -ffreestanding -fshort-wchar \
            -mno-red-zone \
            -Wall -Wextra \
            -e efi_main \
            -Wl,--subsystem,10 \
            -o cube.efi cube.c \
            -L"$LIB" -lgnuefi -lefi

      - uses: actions/upload-artifact@v4
        with:
          name: cube.efi
          path: cube.efi
