name: Build Cube
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          gcc -nostdlib -ffreestanding -fshort-wchar -mno-red-zone \
              -e efi_main -Wl,--subsystem=10 -o cube.efi cube.c
      - uses: actions/upload-artifact@v4
        with:
          name: cube.efi
          path: cube.efi
